### ISSUE TITLE
install guide?

### ISSUE THREAD

**Issue by psegovias** [c-lorand/ScrapyKeeper#24]
Hi guys, im trying to get this project work, but im stuck in this: 

```
root@scrapy:~/ScrapyKeeper# scrapyd-deploy --build-egg output.egg
/usr/local/bin/scrapyd-deploy:23: ScrapyDeprecationWarning: Module `scrapy.utils.http` is deprecated, Please import from `w3lib.http` instead.
  from scrapy.utils.http import basic_auth_header
Error: no Scrapy project found in this location
```

Where i must run that command? im new on the scrapy world. 

Regards!

**Comment by c-lorand** [comment]
Hi,
You have to run that command in the folder where you created your scrapy project.

Regards

**Comment by psegovias** [comment]
Thanks for your reply, i got this:

```
root@scrapy:~/scrap1# scrapyd-deploy --build-egg output.egg
/usr/local/bin/scrapyd-deploy:23: ScrapyDeprecationWarning: Module `scrapy.utils.http` is deprecated, Please import from `w3lib.http` instead.
  from scrapy.utils.http import basic_auth_header
Writing egg to output.egg
```

When upload got this:

```
{
  "code": 500, 
  "data": null, 
  "msg": "HTTPConnectionPool(host='localhost', port=6800): Max retries exceeded with url: /addversion.json (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f9ad807cf98>: Failed to establish a new connection: [Errno 111] Connection refused',))", 
  "success": false
}
```

**Comment by c-lorand** [comment]
Maybe @georgetutuianu can help you with this one

**Comment by georgetutuianu** [comment]
Hi @psegovias! To run the scrapy spiders using Scrapykeeper you also need to have a scrapyd server running [https://scrapyd.readthedocs.io/en/stable/overview.html](https://scrapyd.readthedocs.io/en/stable/overview.html)

Scrapyd is the daemon that will take care to run your spiders (written in scrapy), while scrapykeeper is just an interface over scrapyd.

**Comment by psegovias** [comment]
Thanks, now i have scrapyd and scrapykeeper running, i can upload my egg too, but when i try to load with my arguments i got this:

```
{
  "code": 500, 
  "data": null, 
  "msg": "dictionary update sequence element #0 has length 6; 2 is required", 
  "success": false
}
```

**Comment by georgetutuianu** [comment]
You're getting this error when you're trying to run a spider using `RunOnce` option or when?
Can you try to schedule the spider directly using scrapyd and let me know if you still get an error @ [https://scrapyd.readthedocs.io/en/stable/api.html#schedule-json](https://scrapyd.readthedocs.io/en/stable/api.html#schedule-json)

I'm trying to figure if the error comes from scrapykeeper or from scrapyd

**Comment by psegovias** [comment]
I got this error when i setup i try to use the `RunOnce` option, and the `Periodic Jobs` too, maybe because my scrapy project use more than 2 args?

**Comment by georgetutuianu** [comment]
Can we give us all the arguments that you are trying to use?

**Comment by psegovias** [comment]
`-a email='xxx@xxx.com' -a password='xxx' -a post='https://mbasic.facebook.com/xxx' -a lang='en' -o id.csv`

Im using this scrapy project thttps://github.com/rugantio/fbcrawl

**Comment by c-lorand** [comment]
I guess you'll have to do some debugging to see why this is happening.
It's not an usual case so can't really help you unless I setup this project on my local as well.

Also, as  side note: this project is modified to fulfil our needs and has some functionality that you may not need. For something simpler you should use the repo from which I forked.
